version: 2.1
workflows:
  version: 2
  bolinette_cli:
    jobs:
      - deploy_cli:
          filters:
            tags:
              only: /(?:[\d]+\.){2}[\d]+/
            branches:
              ignore: /.*/

jobs:
  deploy_cli:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            make install
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Create packages
          command: |
            source venv/bin/activate
            make package
      - run:
          name: Upload to pypi
          command: |
            source venv/bin/activate
            twine upload dist/*